FROM openjdk:8u222-jdk-stretch AS build_process
WORKDIR /work
COPY . /work
RUN ./mvnw clean package -DskipTests

FROM openjdk:8u222-jre-stretch
WORKDIR /deploy
COPY --from=build_process /work/target/hello.jar hello.jar
EXPOSE 8080
CMD java -Xmx400m -Xms400m -XX:TieredStopAtLevel=1 -noverify -jar hello.jar