FROM maven:3.6.1-jdk-8 AS build_process
WORKDIR /work
COPY . /work
RUN mvn clean package -DskipTests

FROM openjdk:8u222-jre-stretch
WORKDIR /deploy
COPY --from=build_process /work/target/hello.jar hello.jar
EXPOSE 8080
CMD java -Xmx400m -Xms400m  -XX:TieredStopAtLevel=1 -noverify -jar hello.jar